version: "3.8"
services:
  server:
    image: "withsang/t3-excuse:latest" # build from Dockerfile
    ports:
      - "${EXPORT_PORT:?}:80"
    environment:
      - HOST=${HOST:?}
      - MONGO_CONNECTION_URI=mongodb://db:27017/t3
      - OPENAI_API_KEY=${OPENAI_API_KEY:?}
    depends_on:
      - db
  db:
    image: mongo:6.0
    volumes:
      - db-data:/data/db

volumes:
  db-data:
    external: true
